### ISSUE TITLE
Wrong display position

### ISSUE THREAD

**Issue by Yurinann** [Focamacho/MyServerIsCompatible#1]
When I use this mod, the text I originally centered will be forced to move to the next line.
For Example:

Before
                                                                                    AAAAAAAAA BBBBBBBBB

After
                                                                                    AAAAAAAAA
BBBBBBBBB

**Comment by Yurinann** [comment]
![image](https://user-images.githubusercontent.com/75569395/133890368-522cba0c-33e1-48c6-a6d5-cb7f4f5d879c.png)

**Comment by focamacho** [comment]
Not sure if I understood, do you have some in-game screenshots?

**Comment by Yurinann** [comment]
Sorry for the late reply
pictures:

before
![image](https://user-images.githubusercontent.com/75569395/134937601-0fb069a7-eca2-459c-a797-201b1badc71e.png)

after
![image](https://user-images.githubusercontent.com/75569395/134937723-a3f09f68-dfc1-4da3-a4e8-9c3a237c2c39.png)

like these

**Comment by Yurinann** [comment]
@focamacho Hi!

**Comment by Yurinann** [comment]
Waiting for reply, thanks.
