### ISSUE TITLE
[1.17.1] Mod seems to have stopped working in newer forge versions.

### ISSUE THREAD

**Issue by Gbergz** [Focamacho/MyServerIsCompatible#2]
Title^ 

Updated Forge to version **37.0.82** and the red X in server list is once again displayed despite having the mod installed.
![image](https://user-images.githubusercontent.com/26634554/136235834-6fb76a22-4b93-4823-a4ce-eaa66f4c8df9.png)

**-** Gbergz

**Comment by focamacho** [comment]
Thanks for the report!
